#!/bin/sh

cp -r 0.org 0
blockMesh
decomposePar -force
mpirun -np 4 pimpleFoamHFDIB -parallel
reconstructPar
postProcess -func vorticity
foamToVTK

# ----------------------------------------------------------------- end-of-file
